import React, { useEffect, useState } from 'react';
import { StyleSheet, ScrollView, View } from 'react-native';
import { Card, Text, Title, Paragraph, Button, Chip, ActivityIndicator } from 'react-native-paper';
import { useTranslation } from 'react-i18next';
import { AgroApiService, IdentityService, FarmerIdentity, RuleBasedAdvisoryResponse, AdvisoryRecord } from '../../src/services/api';
import { SampleFarm } from '../../src/data/sampleFarms';
import { SampleFarmState } from '../../src/services/sampleFarmState';
import SampleFarmBanner from '../../src/components/SampleFarmBanner';

export default function AdvisoryScreen() {
  const { t } = useTranslation();
  const [savedIdentity, setSavedIdentity] = useState<FarmerIdentity | null>(null);
  const [activeSampleFarm, setActiveSampleFarm] = useState<SampleFarm | null>(null);
  const [advisoryData, setAdvisoryData] = useState<RuleBasedAdvisoryResponse | null>(null);
  const [records, setRecords] = useState<AdvisoryRecord[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadAdvisory();
  }, []);

  const loadAdvisory = async () => {
    setLoading(true);
    try {
      // 1. Check real saved identity
      const identity = await IdentityService.getSavedIdentity();
      setSavedIdentity(identity);

      // 2. Check if a sample farm preview is active
      const currentSample = await SampleFarmState.getActiveSampleFarm();
      if (currentSample) {
        setActiveSampleFarm(currentSample);
        setAdvisoryData({
          farm_id: 999,
          crop_type: currentSample.crop_type,
          latest_telemetry: {
            id: 999,
            farm_id: 999,
            soil_moisture: currentSample.telemetry.soil_moisture,
            temperature_c: currentSample.telemetry.temperature_c,
            humidity_pct: currentSample.telemetry.humidity_pct,
            nitrogen_ppm: currentSample.telemetry.nitrogen_ppm,
            phosphorus_ppm: currentSample.telemetry.phosphorus_ppm,
            potassium_ppm: currentSample.telemetry.potassium_ppm,
            soil_ph: currentSample.telemetry.soil_ph,
            timestamp: new Date().toISOString()
          },
          irrigation_advice: currentSample.advisory.irrigation_advice,
          npk_advice: currentSample.advisory.npk_advice,
          ph_advice: `Soil pH is ${currentSample.telemetry.soil_ph} (${currentSample.condition_label})`,
          advisory_records: currentSample.advisory.advisory_records as any
        });
        setRecords(currentSample.advisory.advisory_records as any);
        setLoading(false);
        return;
      }

      // 3. Normal Flow: Load Real Farm Advisory from Backend
      setActiveSampleFarm(null);
      const farmId = identity?.farm_id || 1;
      const res = await AgroApiService.getAdvisories(farmId);
      setAdvisoryData(res.data);
      setRecords(res.data.advisory_records || []);
    } catch (err) {
      console.warn('Advisory loading error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleExitSampleMode = async () => {
    await SampleFarmState.clearSampleFarmMode();
    setActiveSampleFarm(null);
    loadAdvisory();
  };

  const handleMarkAsRead = (id: number) => {
    setRecords((prev) =>
      prev.map((rec) => (rec.id === id ? { ...rec, is_read: true } : rec))
    );
  };

  const getAdvisoryBadge = (type: string) => {
    switch (type.toLowerCase()) {
      case 'disease':
        return { label: 'DISEASE ALERT', bg: '#FFEBEE', text: '#C62828', icon: '🔴' };
      case 'irrigation':
        return { label: 'IRRIGATION NEEDED', bg: '#E3F2FD', text: '#1565C0', icon: '💧' };
      case 'npk':
        return { label: 'NPK NUTRIENT', bg: '#E8F5E9', text: '#2E7D32', icon: '🧪' };
      default:
        return { label: 'GENERAL ADVISORY', bg: '#FFF3E0', text: '#E65100', icon: '📢' };
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      {/* 1. SAMPLE DATA WARNING BANNER IF IN EXPLORE MODE */}
      {activeSampleFarm && (
        <SampleFarmBanner
          sampleFarm={activeSampleFarm}
          onExitSampleMode={handleExitSampleMode}
        />
      )}

      {/* 2. OVERVIEW AI ADVISORY CARD */}
      <Card style={[styles.headerCard, activeSampleFarm ? styles.headerCardSample : null]}>
        <Card.Content>
          <View style={styles.headerTitleRow}>
            <Title style={styles.headerTitle}>
              {activeSampleFarm ? '🧪 Simulated Agronomic Prescription' : '🌱 Precision Agronomic Prescription'}
            </Title>
            {activeSampleFarm && (
              <Chip style={styles.sampleBadge} textStyle={{ color: '#FFF', fontSize: 10, fontWeight: 'bold' }}>
                SAMPLE SCENARIO
              </Chip>
            )}
          </View>

          <Paragraph style={styles.subText}>
            Generated by Krishi Setu AI for{' '}
            {activeSampleFarm
              ? `${activeSampleFarm.name} (${activeSampleFarm.crop_type}) — ${activeSampleFarm.scenario_title}`
              : savedIdentity
              ? `${savedIdentity.farm_name} (${savedIdentity.crop_type})`
              : 'Wheat Plot'}
          </Paragraph>

          {loading ? (
            <ActivityIndicator style={{ marginVertical: 16 }} color="#2E7D32" />
          ) : (
            <View style={{ marginTop: 8 }}>
              {/* Irrigation Advice */}
              <View style={styles.adviceBox}>
                <Text style={styles.adviceBoxTitle}>💧 Irrigation Prescription:</Text>
                <Text style={styles.adviceBoxText}>{advisoryData?.irrigation_advice}</Text>
              </View>

              {/* NPK Advice */}
              <View style={[styles.adviceBox, { backgroundColor: '#E8F5E9', marginTop: 10 }]}>
                <Text style={[styles.adviceBoxTitle, { color: '#1B5E20' }]}>🧪 NPK Nutrient Prescription:</Text>
                <Text style={[styles.adviceBoxText, { color: '#2E7D32' }]}>{advisoryData?.npk_advice}</Text>
              </View>

              {/* Action Items for Sample Farms */}
              {activeSampleFarm?.advisory.action_items && (
                <View style={[styles.adviceBox, { backgroundColor: '#F3E5F5', marginTop: 10 }]}>
                  <Text style={[styles.adviceBoxTitle, { color: '#6A1B9A' }]}>📋 Recommended Action Checklist:</Text>
                  {activeSampleFarm.advisory.action_items.map((item, idx) => (
                    <Text key={idx} style={{ color: '#4A148C', fontSize: 12, marginTop: 3 }}>
                      • {item}
                    </Text>
                  ))}
                </View>
              )}
            </View>
          )}
        </Card.Content>
      </Card>

      {/* 3. ADVISORY RECORDS TIMELINE */}
      <Title style={styles.sectionHeader}>
        {activeSampleFarm ? `📋 Scenario Advisory Logs (${records.length})` : `📋 All Advisory Logs (${records.length})`}
      </Title>

      {records.map((rec) => {
        const badge = getAdvisoryBadge(rec.type);
        return (
          <Card key={rec.id} style={[styles.recordCard, rec.is_read && { opacity: 0.75 }]}>
            <Card.Content>
              <View style={styles.cardHeaderRow}>
                <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                  <Text style={{ fontSize: 16, marginRight: 6 }}>{badge.icon}</Text>
                  <Text style={{ fontWeight: 'bold', color: badge.text }}>{badge.label}</Text>
                </View>

                {rec.is_read ? (
                  <Chip icon="check-all" style={styles.readChip} textStyle={{ fontSize: 10 }}>Read</Chip>
                ) : (
                  <Chip style={{ backgroundColor: '#FFEBEE' }} textStyle={{ fontSize: 10 }}>UNREAD</Chip>
                )}
              </View>

              <Paragraph style={styles.recordMessage}>{rec.message}</Paragraph>

              <View style={styles.cardFooterRow}>
                <Text style={styles.dateText}>
                  🕒 {new Date(rec.created_at).toLocaleDateString()} {new Date(rec.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </Text>
                {!rec.is_read && (
                  <Button
                    mode="text"
                    compact
                    onPress={() => handleMarkAsRead(rec.id)}
                    labelStyle={{ color: '#2E7D32', fontSize: 12 }}
                  >
                    Mark as Read ✓
                  </Button>
                )}
              </View>
            </Card.Content>
          </Card>
        );
      })}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F7F4',
  },
  content: {
    padding: 16,
    paddingBottom: 36,
  },
  headerCard: {
    backgroundColor: '#FFFFFF',
    marginBottom: 16,
    borderRadius: 14,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E8EFE8',
  },
  headerCardSample: {
    borderColor: '#FFA000',
    borderWidth: 1.5,
  },
  headerTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  headerTitle: {
    color: '#1B5E20',
    fontSize: 18,
    fontWeight: 'bold',
    flex: 1,
    minWidth: 140,
  },
  sampleBadge: {
    backgroundColor: '#FF6F00',
    height: 22,
  },
  subText: {
    color: '#666666',
    fontSize: 12,
    marginBottom: 8,
    marginTop: 2,
  },
  sectionHeader: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#1B5E20',
    marginBottom: 12,
  },
  adviceBox: {
    backgroundColor: '#FFF3E0',
    padding: 12,
    borderRadius: 10,
  },
  adviceBoxTitle: {
    fontWeight: 'bold',
    color: '#E65100',
    marginBottom: 4,
    fontSize: 13,
  },
  adviceBoxText: {
    color: '#D84315',
    fontSize: 13,
    lineHeight: 18,
  },
  recordCard: {
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
    borderRadius: 12,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E8EFE8',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  readChip: {
    backgroundColor: '#F5F5F5',
  },
  recordMessage: {
    fontSize: 13.5,
    color: '#333333',
    lineHeight: 19,
    marginVertical: 4,
  },
  cardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  dateText: {
    fontSize: 11,
    color: '#888888',
  },
});
