import React, { useEffect, useState } from 'react';
import { StyleSheet, ScrollView, View } from 'react-native';
import { Card, Text, Title, Paragraph, Button, Chip, ActivityIndicator } from 'react-native-paper';
import { useTranslation } from 'react-i18next';
import { AgroApiService, IdentityService, FarmerIdentity, RuleBasedAdvisoryResponse, AdvisoryRecord } from '../../src/services/api';

export default function AdvisoryScreen() {
  const { t } = useTranslation();
  const [savedIdentity, setSavedIdentity] = useState<FarmerIdentity | null>(null);
  const [advisoryData, setAdvisoryData] = useState<RuleBasedAdvisoryResponse | null>(null);
  const [records, setRecords] = useState<AdvisoryRecord[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadAdvisory();
  }, []);

  const loadAdvisory = async () => {
    setLoading(true);
    try {
      const identity = await IdentityService.getSavedIdentity();
      setSavedIdentity(identity);
      const farmId = identity?.farm_id || 1;

      const res = await AgroApiService.getAdvisories(farmId);
      setAdvisoryData(res.data);
      setRecords(res.data.advisory_records || []);
    } catch (err) {
      console.warn('Advisory loading error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleMarkAsRead = (id: number) => {
    setRecords((prev) =>
      prev.map((rec) => (rec.id === id ? { ...rec, is_read: true } : rec))
    );
  };

  const getAdvisoryBadge = (type: string) => {
    switch (type.toLowerCase()) {
      case 'disease':
        return { label: 'DISEASE ALERT', bg: '#FFEBEE', text: '#C62828', icon: '🔴' };
      case 'irrigation':
        return { label: 'IRRIGATION NEEDED', bg: '#E3F2FD', text: '#1565C0', icon: '💧' };
      case 'npk':
        return { label: 'NPK NUTRIENT', bg: '#E8F5E9', text: '#2E7D32', icon: '🧪' };
      default:
        return { label: 'GENERAL ADVISORY', bg: '#FFF3E0', text: '#E65100', icon: '📢' };
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      {/* Overview AI Advisory Card */}
      <Card style={styles.headerCard}>
        <Card.Content>
          <Title style={styles.headerTitle}>🌱 Precision Agronomic Prescription</Title>
          <Paragraph style={styles.subText}>
            Generated by Krishi Setu AI for {savedIdentity ? `${savedIdentity.farm_name} (${savedIdentity.crop_type})` : 'Wheat Plot'}
          </Paragraph>

          {loading ? (
            <ActivityIndicator style={{ marginVertical: 16 }} color="#2E7D32" />
          ) : (
            <View style={{ marginTop: 8 }}>
              {/* Irrigation Advice */}
              <View style={styles.adviceBox}>
                <Text style={styles.adviceBoxTitle}>💧 Irrigation Prescription:</Text>
                <Text style={styles.adviceBoxText}>{advisoryData?.irrigation_advice}</Text>
              </View>

              {/* NPK Advice */}
              <View style={[styles.adviceBox, { backgroundColor: '#E8F5E9', marginTop: 10 }]}>
                <Text style={[styles.adviceBoxTitle, { color: '#1B5E20' }]}>🧪 NPK Nutrient Prescription:</Text>
                <Text style={[styles.adviceBoxText, { color: '#2E7D32' }]}>{advisoryData?.npk_advice}</Text>
              </View>
            </View>
          )}
        </Card.Content>
      </Card>

      {/* Advisory Records Timeline Header */}
      <Title style={styles.sectionHeader}>📋 All Advisory Logs ({records.length})</Title>

      {records.map((rec) => {
        const badge = getAdvisoryBadge(rec.type);
        return (
          <Card key={rec.id} style={[styles.recordCard, rec.is_read && { opacity: 0.75 }]}>
            <Card.Content>
              <View style={styles.cardHeaderRow}>
                <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                  <Text style={{ fontSize: 16, marginRight: 6 }}>{badge.icon}</Text>
                  <Text style={{ fontWeight: 'bold', color: badge.text }}>{badge.label}</Text>
                </View>

                {rec.is_read ? (
                  <Chip icon="check-all" style={styles.readChip}>Read</Chip>
                ) : (
                  <Chip style={{ backgroundColor: '#FFEBEE' }}>UNREAD</Chip>
                )}
              </View>

              <Paragraph style={styles.recordMessage}>{rec.message}</Paragraph>

              <View style={styles.cardFooterRow}>
                <Text style={styles.dateText}>
                  🕒 {new Date(rec.created_at).toLocaleDateString()} {new Date(rec.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </Text>
                {!rec.is_read && (
                  <Button
                    mode="text"
                    compact
                    onPress={() => handleMarkAsRead(rec.id)}
                    labelStyle={{ color: '#2E7D32', fontSize: 12 }}
                  >
                    Mark as Read ✓
                  </Button>
                )}
              </View>
            </Card.Content>
          </Card>
        );
      })}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F7F4',
  },
  content: {
    padding: 16,
  },
  headerCard: {
    backgroundColor: '#FFFFFF',
    marginBottom: 16,
    borderRadius: 12,
    elevation: 2,
  },
  headerTitle: {
    color: '#1B5E20',
    fontSize: 18,
    fontWeight: 'bold',
  },
  subText: {
    color: '#666666',
    fontSize: 12,
    marginBottom: 8,
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1B5E20',
    marginBottom: 12,
  },
  adviceBox: {
    backgroundColor: '#FFF3E0',
    padding: 12,
    borderRadius: 8,
  },
  adviceBoxTitle: {
    fontWeight: 'bold',
    color: '#E65100',
    marginBottom: 4,
  },
  adviceBoxText: {
    color: '#D84315',
    fontSize: 13,
    lineHeight: 18,
  },
  recordCard: {
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
    borderRadius: 10,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  readChip: {
    backgroundColor: '#F5F5F5',
  },
  recordMessage: {
    fontSize: 14,
    color: '#333333',
    lineHeight: 20,
    marginVertical: 4,
  },
  cardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  dateText: {
    fontSize: 11,
    color: '#888888',
  },
});
